In [1]:
import numpy as np

na = np.array([2, 6, 8, 9])

In [2]:
print(na)

[2 6 8 9]


In [3]:
nb = np.arange(10, 100, 3)

In [4]:
print(nb)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]


In [5]:
na.ndim

1

In [6]:
na.size

4

In [7]:
len(na)

4

In [8]:
lista = [10, 23, 55, 43, 77, 20]
listb = [11, 19, 32, 74, 81, 5] 

In [9]:
nc = np.array([lista, listb])

In [10]:
print(nc)

[[10 23 55 43 77 20]
 [11 19 32 74 81  5]]


In [11]:
nc.ndim

2

In [12]:
len(nc)

2

In [13]:
nc.shape

(2, 6)

In [14]:
nc.size

12

In [15]:
nc.reshape(3, 4)

array([[10, 23, 55, 43],
       [77, 20, 11, 19],
       [32, 74, 81,  5]])

In [16]:
nc

array([[10, 23, 55, 43, 77, 20],
       [11, 19, 32, 74, 81,  5]])

In [17]:
nd = nc.reshape(3, 4)

In [18]:
nd

array([[10, 23, 55, 43],
       [77, 20, 11, 19],
       [32, 74, 81,  5]])

In [19]:
nd.reshape(-1, 3)

array([[10, 23, 55],
       [43, 77, 20],
       [11, 19, 32],
       [74, 81,  5]])

In [20]:
nd.reshape(3, -1)

array([[10, 23, 55, 43],
       [77, 20, 11, 19],
       [32, 74, 81,  5]])

In [23]:
ne = np.linspace(1, 100, 10)

In [24]:
print(ne)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [25]:
nf = np.linspace(0, 2, 5)

print(nf)

[0.  0.5 1.  1.5 2. ]


In [26]:
nd

array([[10, 23, 55, 43],
       [77, 20, 11, 19],
       [32, 74, 81,  5]])

In [28]:
ng = np.array([[5, 8, 1, 2], [3, 6, 9, 2], [4, 6, 2, 1]])

print(ng)

[[5 8 1 2]
 [3 6 9 2]
 [4 6 2 1]]


In [29]:
print(nd)

[[10 23 55 43]
 [77 20 11 19]
 [32 74 81  5]]


In [30]:
ng + nd

array([[15, 31, 56, 45],
       [80, 26, 20, 21],
       [36, 80, 83,  6]])

In [31]:
ng * nd

array([[ 50, 184,  55,  86],
       [231, 120,  99,  38],
       [128, 444, 162,   5]])

In [33]:
nh = np.array([[[5, 8, 1, 2], [3, 6, 9, 2]], [[4, 6, 2, 1], [11, 22, 33, 44]]])

print(nh)

[[[ 5  8  1  2]
  [ 3  6  9  2]]

 [[ 4  6  2  1]
  [11 22 33 44]]]


In [34]:
nh.size

16

In [37]:
ni = nh.reshape(4, 4 )

print(ni)

[[ 5  8  1  2]
 [ 3  6  9  2]
 [ 4  6  2  1]
 [11 22 33 44]]


In [38]:
ni.ndim

2

In [39]:
nh.ndim

3

In [41]:
nj = np.zeros((4, 3))

print(nj)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [43]:
nk = np.ones((4, 3))

print(nk)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
nl = np.full((4, 3), fill_value=17)

print(nl)

[[17 17 17]
 [17 17 17]
 [17 17 17]
 [17 17 17]]


In [45]:
print(ni)

[[ 5  8  1  2]
 [ 3  6  9  2]
 [ 4  6  2  1]
 [11 22 33 44]]


In [46]:
print(ni.T)

[[ 5  3  4 11]
 [ 8  6  6 22]
 [ 1  9  2 33]
 [ 2  2  1 44]]


In [47]:
nm = np.array([[5, 8, 1, 2], [3, 6, 9, 2], [4, 6, 2, 1]], dtype="int8")

print(nm)

[[5 8 1 2]
 [3 6 9 2]
 [4 6 2 1]]


In [48]:
ni.dtype

dtype('int64')

In [49]:
nm.dtype

dtype('int8')

In [50]:
listu = [74, 81, 50] 
listx = [10, 23, 55]
listy = [43, 77, 20]
listz = [11, 19, 32]

In [51]:
nn = np.array([listu, listx, listy, listz], dtype="uint8")

In [52]:
nn.dtype

dtype('uint8')

In [53]:
print(nn)

[[74 81 50]
 [10 23 55]
 [43 77 20]
 [11 19 32]]


In [54]:
listu = [74, 81, 50] 
listx = [10, 23, 260]
listy = [43, 77, 20]
listz = [11, 19, 32]

no = np.array([listu, listx, listy, listz], dtype="uint8")

print(no)

[[74 81 50]
 [10 23  4]
 [43 77 20]
 [11 19 32]]


In [55]:
# random

In [56]:
np.random.randint(23)

16

In [57]:
np.random.randint(23)

18

In [59]:
np.random.rand()

0.8941734863508497

In [60]:
np.random.rand()

0.5261628163448572

In [61]:
np.random.randint(0, 189, size=(6))

array([ 59,  70,  19, 162, 149, 143])

In [62]:
np.random.randint(0, 189, size=(6))

array([135,  56, 180, 164, 111,  44])

In [63]:
np.random.randint(0, 189, size=(4, 6))

array([[ 21,  96, 175,  88,  77,  39],
       [168,  97, 143,  60, 123,  32],
       [125,  55, 168,  18, 109,  98],
       [ 74, 122, 154,  31,   8, 119]])

In [64]:
nq = np.random.randint(0, 189, size=(4, 6))

In [65]:
nq

array([[104, 123, 141, 109,  18,  92],
       [ 38,  60, 134,  31,   8,  82],
       [109, 135, 127,   1,  55,  10],
       [ 41,  64,  10,  27,  30, 110]])

In [66]:
lista = [10, 23, 55, 43, 77, 20]
listb = [11, 19, 32, 74, 81, 5] 

num = np.random.choice(lista)
print(num)

20


In [67]:
num = np.random.choice(lista)
print(num)

23


In [68]:
num = np.random.choice(lista, size=(2, 3))
print(num)

[[77 23 55]
 [77 77 55]]


In [69]:
nq

array([[104, 123, 141, 109,  18,  92],
       [ 38,  60, 134,  31,   8,  82],
       [109, 135, 127,   1,  55,  10],
       [ 41,  64,  10,  27,  30, 110]])

In [70]:
np.random.shuffle(nq)

In [71]:
nq

array([[109, 135, 127,   1,  55,  10],
       [ 38,  60, 134,  31,   8,  82],
       [104, 123, 141, 109,  18,  92],
       [ 41,  64,  10,  27,  30, 110]])

In [72]:
np.random.permutation(nq)

array([[109, 135, 127,   1,  55,  10],
       [104, 123, 141, 109,  18,  92],
       [ 38,  60, 134,  31,   8,  82],
       [ 41,  64,  10,  27,  30, 110]])

In [73]:
nq

array([[109, 135, 127,   1,  55,  10],
       [ 38,  60, 134,  31,   8,  82],
       [104, 123, 141, 109,  18,  92],
       [ 41,  64,  10,  27,  30, 110]])

In [74]:
print(lista)

[10, 23, 55, 43, 77, 20]


In [75]:
nr = np.random.choice(lista, p=[0.2, 0.2, 0.2, 0.4, 0.0, 0.0], size=(5,4))

print(nr)

[[23 23 43 55]
 [43 55 10 10]
 [43 23 43 23]
 [10 43 43 43]
 [43 10 23 10]]


In [76]:
ns = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(ns)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [78]:
ns[0][2]

30

In [79]:
print(ns)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [80]:
print(ns[1:])

[[40 50 60]
 [70 80 90]]


In [81]:
print(ns[1:, :2])

[[40 50]
 [70 80]]


In [82]:
print(ns[1:2, :])

[[40 50 60]]


In [83]:
print(ns[:2, 1])

[20 50]


In [84]:
nq.mean()

69.125

In [85]:
nq

array([[109, 135, 127,   1,  55,  10],
       [ 38,  60, 134,  31,   8,  82],
       [104, 123, 141, 109,  18,  92],
       [ 41,  64,  10,  27,  30, 110]])

In [86]:
nq.size

24

In [87]:
nq.min()

1

In [88]:
nq.max()

141

In [89]:
nq.std()

46.337810784858334

In [90]:
nq.sum()

1659

In [91]:
sum(nq)

array([292, 382, 412, 168, 111, 294])

In [92]:
nq.var()

2147.1927083333335

In [93]:
nr

array([[23, 23, 43, 55],
       [43, 55, 10, 10],
       [43, 23, 43, 23],
       [10, 43, 43, 43],
       [43, 10, 23, 10]])

In [94]:
np.square(nr)

array([[ 529,  529, 1849, 3025],
       [1849, 3025,  100,  100],
       [1849,  529, 1849,  529],
       [ 100, 1849, 1849, 1849],
       [1849,  100,  529,  100]])

In [95]:
np.power(nr, 3)

array([[ 12167,  12167,  79507, 166375],
       [ 79507, 166375,   1000,   1000],
       [ 79507,  12167,  79507,  12167],
       [  1000,  79507,  79507,  79507],
       [ 79507,   1000,  12167,   1000]])

In [96]:
nq.flatten()

array([109, 135, 127,   1,  55,  10,  38,  60, 134,  31,   8,  82, 104,
       123, 141, 109,  18,  92,  41,  64,  10,  27,  30, 110])

In [100]:
np.random.seed(10)

num = np.random.choice(lista)
print(num)

23


In [101]:
np.random.seed(10)

num = np.random.choice(lista)
print(num)

23


In [102]:
np.random.seed(10)

num = np.random.choice(lista)
print(num)

23


In [103]:
type(nq)

numpy.ndarray

In [104]:
nq.itemsize

8

In [105]:
nq.nbytes

192